/*
 * Auto-generated TFLite model data for SensorFusion-HAR Lite.
 *
 * PLACEHOLDER: This file will be regenerated by the Colab notebook
 * after training and TFLite conversion. The actual model bytes will
 * replace the empty array below.
 *
 * Usage: #include "model_data.h"
 *        const tflite::Model* model = tflite::GetModel(model_tflite);
 */

#ifndef MODEL_DATA_H
#define MODEL_DATA_H

// Placeholder — replace with actual model bytes from notebook output
alignas(8) const unsigned char model_tflite[] = {
    0x00  // placeholder byte
};
const unsigned int model_tflite_len = sizeof(model_tflite);

#endif  // MODEL_DATA_H
