/*
 * ESP32 Serial-Inference Sketch
 * ==============================
 * Receives a normalised sensor window from the laptop (JSON array over USB
 * Serial), runs TFLite-Micro inference, and replies with the prediction JSON.
 *
 * Protocol (laptop → ESP32, newline-terminated):
 *   {"w":[[ax,ay,az,gx,gy,gz], ...]}   (50 rows × 6 cols, already normalised)
 *
 * Protocol (ESP32 → laptop, newline-terminated):
 *   {"label":"Walking","conf":0.87,"class":0,"ms":12.3}
 *
 * The laptop server.py sends normalised windows (post gravity-align + z-score)
 * so the ESP32 only needs TFLite inference — no sensor reading or normalisation.
 *
 * Flash with:
 *   arduino-cli compile --fqbn esp32:esp32:esp32 esp32_serial_inference/
 *   arduino-cli upload  --fqbn esp32:esp32:esp32 -p <PORT> esp32_serial_inference/
 */

#include <Arduino.h>
#include "model_data.h"          // generated by export_tflite.py

#include <TensorFlowLite_ESP32.h>
#include "tensorflow/lite/micro/all_ops_resolver.h"
#include "tensorflow/lite/micro/micro_interpreter.h"
#include "tensorflow/lite/schema/schema_generated.h"

// ---------------------------------------------------------------------------
// Configuration
// ---------------------------------------------------------------------------
#define NUM_CLASSES   11
#define TIME_STEPS    50
#define NUM_CHANNELS  6
#define BAUD_RATE     460800      // high baud for low-latency window transfer
#define TENSOR_ARENA_SIZE (72 * 1024)

static const char* ACTIVITY_LABELS[NUM_CLASSES] = {
    "Walking", "Sitting", "Standing", "Lying Down",
    "Stairs Up", "Stairs Down", "Jogging", "Jumping",
    "Cycling", "Running", "Waist Bending"
};

// ---------------------------------------------------------------------------
// TFLite globals
// ---------------------------------------------------------------------------
static uint8_t tensor_arena[TENSOR_ARENA_SIZE];
static tflite::MicroInterpreter* interpreter = nullptr;
static TfLiteTensor* input_tensor  = nullptr;
static TfLiteTensor* output_tensor = nullptr;

// ---------------------------------------------------------------------------
// JSON input buffer
// ---------------------------------------------------------------------------
#define MAX_LINE 4096
static char line_buf[MAX_LINE];
static int  line_len = 0;

// ---------------------------------------------------------------------------
bool tflm_init() {
    const tflite::Model* model = tflite::GetModel(model_tflite);
    if (model->version() != TFLITE_SCHEMA_VERSION) {
        Serial.println("{\"error\":\"schema_mismatch\"}");
        return false;
    }
    static tflite::AllOpsResolver resolver;
    static tflite::MicroInterpreter static_interp(
        model, resolver, tensor_arena, TENSOR_ARENA_SIZE);
    interpreter = &static_interp;

    if (interpreter->AllocateTensors() != kTfLiteOk) {
        Serial.println("{\"error\":\"alloc_tensors_failed\"}");
        return false;
    }
    input_tensor  = interpreter->input(0);
    output_tensor = interpreter->output(0);

    Serial.print("{\"ready\":true,\"arena_bytes\":");
    Serial.print(interpreter->arena_used_bytes());
    Serial.print(",\"input_type\":");
    Serial.print(input_tensor->type);
    Serial.println("}");
    return true;
}

// ---------------------------------------------------------------------------
// Minimal JSON float-array parser.
// Parses the flat sequence of floats from {"w":[[...],[...],...]}
// Returns number of values parsed, or -1 on error.
// ---------------------------------------------------------------------------
static int parse_window(const char* json, float* out, int max_vals) {
    const char* p = json;
    int count = 0;
    // skip to first '['
    while (*p && *p != '[') p++;
    while (*p && count < max_vals) {
        // skip non-numeric
        while (*p && *p != '-' && !(*p >= '0' && *p <= '9')) {
            if (*p == ']' && *(p+1) == '}') goto done;  // end of outer array
            p++;
        }
        if (!*p) break;
        char* end;
        float val = strtof(p, &end);
        if (end == p) break;
        out[count++] = val;
        p = end;
    }
done:
    return count;
}

// ---------------------------------------------------------------------------
void run_inference(float* normed_window) {
    unsigned long t0 = micros();

    if (input_tensor->type == kTfLiteInt8) {
        float scale = input_tensor->params.scale;
        int32_t zp  = input_tensor->params.zero_point;
        int8_t* d   = input_tensor->data.int8;
        for (int i = 0; i < TIME_STEPS * NUM_CHANNELS; i++) {
            int32_t q = (int32_t)roundf(normed_window[i] / scale) + zp;
            d[i] = (int8_t)constrain(q, -128, 127);
        }
    } else {
        float* d = input_tensor->data.f;
        for (int i = 0; i < TIME_STEPS * NUM_CHANNELS; i++)
            d[i] = normed_window[i];
    }

    if (interpreter->Invoke() != kTfLiteOk) {
        Serial.println("{\"error\":\"invoke_failed\"}");
        return;
    }
    float elapsed_ms = (micros() - t0) / 1000.0f;

    // Dequantise output if INT8
    float logits[NUM_CLASSES];
    if (output_tensor->type == kTfLiteInt8) {
        float scale = output_tensor->params.scale;
        int32_t zp  = output_tensor->params.zero_point;
        for (int i = 0; i < NUM_CLASSES; i++)
            logits[i] = ((float)output_tensor->data.int8[i] - zp) * scale;
    } else {
        for (int i = 0; i < NUM_CLASSES; i++)
            logits[i] = output_tensor->data.f[i];
    }

    // Softmax
    float max_l = logits[0];
    for (int i = 1; i < NUM_CLASSES; i++) if (logits[i] > max_l) max_l = logits[i];
    float sum_exp = 0;
    float probs[NUM_CLASSES];
    for (int i = 0; i < NUM_CLASSES; i++) { probs[i] = expf(logits[i] - max_l); sum_exp += probs[i]; }
    for (int i = 0; i < NUM_CLASSES; i++) probs[i] /= sum_exp;

    int best = 0;
    for (int i = 1; i < NUM_CLASSES; i++) if (probs[i] > probs[best]) best = i;

    // Reply JSON
    Serial.print("{\"label\":\"");
    Serial.print(ACTIVITY_LABELS[best]);
    Serial.print("\",\"conf\":");
    Serial.print(probs[best], 4);
    Serial.print(",\"class\":");
    Serial.print(best);
    Serial.print(",\"ms\":");
    Serial.print(elapsed_ms, 2);
    Serial.print(",\"probs\":[");
    for (int i = 0; i < NUM_CLASSES; i++) {
        Serial.print(probs[i], 4);
        if (i < NUM_CLASSES - 1) Serial.print(",");
    }
    Serial.println("]}");
}

// ---------------------------------------------------------------------------
void setup() {
    Serial.begin(BAUD_RATE);
    delay(500);
    Serial.println("{\"boot\":true}");
    if (!tflm_init()) {
        while (true) delay(1000);
    }
}

void loop() {
    while (Serial.available()) {
        char c = Serial.read();
        if (c == '\n' || c == '\r') {
            if (line_len > 0) {
                line_buf[line_len] = '\0';
                static float window[TIME_STEPS * NUM_CHANNELS];
                int n = parse_window(line_buf, window, TIME_STEPS * NUM_CHANNELS);
                if (n == TIME_STEPS * NUM_CHANNELS) {
                    run_inference(window);
                } else {
                    Serial.print("{\"error\":\"bad_window\",\"got\":");
                    Serial.print(n);
                    Serial.println("}");
                }
                line_len = 0;
            }
        } else {
            if (line_len < MAX_LINE - 1)
                line_buf[line_len++] = c;
        }
    }
}
